import type { Metadata } from "next";
import "./globals.css";
import { BackgroundImage } from "@/components/core";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Star Wars - Search Planets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <html lang="pt-BR">
        <BackgroundImage>{children}</BackgroundImage>
      </html>
    </StyledComponentsRegistry>
  );
}
